server:
  port: ${PORT:9090}
spring:
  config:
    import: configserver:http://127.0.0.1:8888
  application:
    name: accountingapi
  cloud:
    discovery:
      enabled: true
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: myroute1
          uri: lb://ACCOUNTING
          predicates:
            - Path=/api/v1/accounting/**
